using HealthMonitorApp.Data;
using HealthMonitorApp.Models;
using HealthMonitorApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;

namespace HealthMonitorApp.Controllers;

public class ApiGroupController : Controller
{
    private readonly ApplicationDbContext _context;

    public ApiGroupController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: List of ApiGroups
    public IActionResult Index()
    {
        return View(_context.ApiGroups.ToList());
    }

    // GET: Create new ApiGroup
    public IActionResult Create()
    {
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("ApiGroup, Variables")] ApiGroupViewModel apiGroupViewModel)
    {
        if (ModelState.IsValid)
        {
            try
            {
                var apiGroup = apiGroupViewModel.ApiGroup;
                _context.Add(apiGroup); // Ensure you're adding the ApiGroup entity

                // Save the apiGroupViewModel to generate its ID if it's generated by the database
                await _context.SaveChangesAsync();

                if (apiGroupViewModel.Variables != null && apiGroupViewModel.Variables.Count > 0)
                {
                    foreach (var variableViewModel in apiGroupViewModel.Variables)
                    {
                        var encryptedValue = Variable.EncryptVariable(variableViewModel.Value); // Assuming EncryptVariable is a static method or accessible here
                        var apiGroupVariable = new ApiGroupVariable
                        {
                            ApiGroupId = apiGroup.Id, // Use the generated Id from the saved ApiGroup
                            Variable = new Variable
                            {
                                Name = variableViewModel.Name,
                                Value = encryptedValue
                            }
                        };
                        _context.ApiGroupVariables.Add(apiGroupVariable); // Assuming your DbContext has a DbSet for ApiGroupVariables
                    }

                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // Log the exception (ex) here or show an error message to the user
                ModelState.AddModelError("", "An error occurred while creating the API Group.");
            }
        }

        // If we got this far, something failed, redisplay form
        return View(apiGroupViewModel);
    }



    // GET: Edit ApiGroup

    public async Task<IActionResult> Edit(Guid id)
    {
        var apiGroup = await _context.ApiGroups.FindAsync(id);
        if (apiGroup == null) return NotFound();
        var apiGroupVariables = await _context.ApiGroupVariables
            .Where(v => v.ApiGroupId == id)
            .Select(v => v.Variable)
            .ToListAsync();
        var variableIds = apiGroupVariables.Select(v => v.Id).ToList();
        List<Variable> variables= _context.Variables.Where(v => variableIds.Contains(v.Id)).ToList();
        ApiGroupViewModel apiGroupViewModel = new ApiGroupViewModel
        {
            ApiGroup = apiGroup,
            Variables = variables
        };
        return View(apiGroupViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(Guid id, [Bind("ApiGroup, Variable")] ApiGroupViewModel apiGroupViewModel)
    {
        if (id != apiGroupViewModel.ApiGroup.Id) return NotFound();

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(apiGroupViewModel.ApiGroup);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApiGroupExists(apiGroupViewModel.ApiGroup.Id))
                    return NotFound();
                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        return View(apiGroupViewModel);
    }

    private bool ApiGroupExists(Guid id)
    {
        return _context.ApiGroups.Any(e => e.Id == id);
    }


    public async Task<IActionResult> Details(Guid id)
    {
        var apiGroup = await _context.ApiGroups.FindAsync(id);
        if (apiGroup == null) return NotFound();
        var apiGroupVariables = await _context.ApiGroupVariables
            .Where(v => v.ApiGroupId == id)
            .Select(v => v.Variable)
            .ToListAsync();
        var variableIds = apiGroupVariables.Select(v => v.Id).ToList();
        List<Variable> variables= _context.Variables.Where(v => variableIds.Contains(v.Id)).ToList();
        ApiGroupViewModel apiGroupViewModel = new ApiGroupViewModel
        {
            ApiGroup = apiGroup,
            Variables = variables
        };
        return View(apiGroupViewModel);
    }


    // GET: Delete ApiGroup
    public async Task<IActionResult> Delete(Guid id)
    {
        var apiGroup = await _context.ApiGroups
            .Include(g => g.ApiEndpoints) 
            .ThenInclude(ae => ae.ServiceStatus)
            .FirstOrDefaultAsync(g => g.Id == id);

        if (apiGroup == null) return NotFound();
        

        return PartialView("_DeleteConfirmation", apiGroup);
    }

    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(Guid id)
    {
        var apiGroup = await _context.ApiGroups
            .Include(g => g.ApiEndpoints)
            .ThenInclude(ae => ae.ServiceStatus)
            .FirstOrDefaultAsync(g => g.Id == id);
        if (apiGroup == null) return NotFound();
        foreach (var apiEndpoint in apiGroup.ApiEndpoints)
        {
            _context.ApiEndpoints.Remove(apiEndpoint);
            _context.ServiceStatuses.Remove(apiEndpoint.ServiceStatus);
        }
        _context.ApiGroups.Remove(apiGroup);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }


    [HttpPost]
    public async Task<IActionResult> FetchAuthToken(string authCurl)
    {
        using (var client = new HttpClient())
        {
            var response = await client.GetAsync(authCurl);
            if (response.IsSuccessStatusCode)
            {
                var responseData = await response.Content.ReadAsStringAsync();
                var jsonObject = JObject.Parse(responseData);
                var keys = jsonObject.Properties().Select(p => p.Name).ToList();
                return Json(new { success = true, keys });
            }

            return Json(new { success = false, message = "Failed to fetch token." });
        }
    }
}